### ISSUE TITLE
Usable for new sites?

### ISSUE THREAD

**Issue by vdboor** [oscaro/django-oscar-adyen#11]
I was looking for a nice Oscar-Adyen integration, and now I'm deciding between this one and https://github.com/machtfit/adyen Sadly I'm not able to see through this code where the integration from `handle_payment()` should start, and where it actually calls the Adyen webservices. Could you clarify that for me? Thanks in advance!

**Comment by vdboor** [comment]
To clarify: in the oscaro code, I can’t see a request being made anywhere, which makes me wonder whether the latest commits have been pushed. Besides `setup.py` noting references the python-requests library.

**Comment by aaugustin** [comment]
We're using the "redirect user to Adyen" flow. Most likely we haven't implemented the webservice API.

However we deal with payment notifications.

**Comment by Exirel** [comment]
I close this since we do not plan to handle more than the Adyen Hosted Payment Pages (HPP).
